# Generated by Django 5.1.15 on 2026-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO-4217 (USD, EUR, JPY) o símbolo cripto.', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('exponent', models.PositiveSmallIntegerField(default=2, help_text='Nº de decimales (dígitos menores). USD=2, JPY=0, BHD=3, BTC=8.')),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('is_crypto', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
                'ordering': ['code'],
            },
        ),
    ]
