# Generated by Django 5.1.15 on 2026-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='investing_pid',
            field=models.CharField(blank=True, default='', help_text='pid de investing.com para el par USD/<code>.', max_length=20),
        ),
    ]
