from django.urls import path

from .api import (
    CurrenciesView,
    EmbedSpinView,
    EmbedStateView,
    GameAssetView,
    GameBuildView,
    GameDetailView,
    GamePaytableView,
    GameSimulateView,
    GameThemeView,
    GamesLobbyView,
    LaunchView,
    MasterFreeRoundsView,
    MasterGamesView,
    MasterOperatorsReportView,
    MasterOperatorsView,
    OperatorGamesView,
    OperatorKeysView,
    OperatorMePlayersView,
    OperatorMeSpinsView,
    OperatorMeView,
    OperatorMeWebhookSecretView,
    OperatorWalletConfigView,
    OperatorWebhookSecretView,
    OperatorPlayersView,
    OperatorPlaysView,
    OperatorSpinsView,
    OperatorUserPasswordView,
    OperatorUsersView,
    PlaySpinView,
    ProviderFreeRoundsView,
    ProviderGamesView,
    ProviderLaunchView,
    SpinView,
    SymbolAssetView,
)

app_name = "app_game"

urlpatterns = [
    path("spin/", SpinView.as_view(), name="spin"),
    path("provider/games/", ProviderGamesView.as_view(), name="provider-games"),
    path("provider/launch/", ProviderLaunchView.as_view(), name="provider-launch"),
    path("provider/free-rounds/", ProviderFreeRoundsView.as_view(), name="provider-free-rounds"),
    path("embed/state/", EmbedStateView.as_view(), name="embed-state"),
    path("embed/spin/", EmbedSpinView.as_view(), name="embed-spin"),
    path("games/", GamesLobbyView.as_view(), name="games-lobby"),
    path("games/<slug:slug>/paytable/", GamePaytableView.as_view(), name="game-paytable"),
    path("play/launch/", LaunchView.as_view(), name="play-launch"),
    path("play/spin/", PlaySpinView.as_view(), name="play-spin"),
    path("currencies/", CurrenciesView.as_view(), name="currencies"),
    path("master/games/", MasterGamesView.as_view(), name="master-games"),
    path("master/games/build/", GameBuildView.as_view(), name="master-games-build"),
    path("master/free-rounds/", MasterFreeRoundsView.as_view(), name="master-free-rounds"),
    path("master/games/<slug:slug>/", GameDetailView.as_view(), name="master-game-detail"),
    path("master/games/<slug:slug>/simulate/", GameSimulateView.as_view(), name="master-simulate"),
    path("master/games/<slug:slug>/theme/", GameThemeView.as_view(), name="game-theme"),
    path("master/games/<slug:slug>/asset/<str:field>/", GameAssetView.as_view(), name="game-asset"),
    path(
        "master/games/<slug:slug>/symbols/<str:code>/asset/",
        SymbolAssetView.as_view(),
        name="symbol-asset",
    ),
    # Gestión de operadores (multi-tenant)
    path("master/operators/", MasterOperatorsView.as_view(), name="master-operators"),
    path("master/reports/operators/", MasterOperatorsReportView.as_view(), name="master-operators-report"),
    path("master/operators/<slug:code>/keys/", OperatorKeysView.as_view(), name="operator-keys"),
    path("master/operators/<slug:code>/webhook-secret/", OperatorWebhookSecretView.as_view(), name="operator-webhook-secret"),
    path("master/operators/<slug:code>/wallet-config/", OperatorWalletConfigView.as_view(), name="operator-wallet-config"),
    path("master/operators/<slug:code>/users/", OperatorUsersView.as_view(), name="operator-users"),
    path("master/operators/<slug:code>/users/<int:user_id>/password/", OperatorUserPasswordView.as_view(), name="operator-user-password"),
    path("master/operators/<slug:code>/players/", OperatorPlayersView.as_view(), name="operator-players"),
    # Back office del propio operador (login de operador)
    path("operator/me/", OperatorMeView.as_view(), name="operator-me"),
    path("operator/me/spins/", OperatorMeSpinsView.as_view(), name="operator-me-spins"),
    path("operator/me/players/", OperatorMePlayersView.as_view(), name="operator-me-players"),
    path("operator/me/webhook-secret/", OperatorMeWebhookSecretView.as_view(), name="operator-me-webhook-secret"),
    path("master/operators/<slug:code>/games/", OperatorGamesView.as_view(), name="operator-games"),
    path("master/operators/<slug:code>/plays/", OperatorPlaysView.as_view(), name="operator-plays"),
    path("master/operators/<slug:code>/spins/", OperatorSpinsView.as_view(), name="operator-spins"),
]
