# Generated by Django 5.1.15 on 2026-07-30 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinAuditLog',
            fields=[
                ('sequence_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('spin_id', models.UUIDField(db_index=True, unique=True)),
                ('operator_id', models.UUIDField(db_index=True)),
                ('external_player_id', models.CharField(db_index=True, help_text='user_id del casino.', max_length=120)),
                ('game_id', models.UUIDField(db_index=True)),
                ('bet_amount', models.BigIntegerField(help_text='En céntimos.')),
                ('win_amount', models.BigIntegerField(help_text='En céntimos.')),
                ('currency', models.CharField(max_length=3)),
                ('matrix_result', models.JSONField()),
                ('winning_lines', models.JSONField(default=list)),
                ('rtp_applied', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rtp_config_id', models.UUIDField()),
                ('math_version', models.CharField(max_length=40)),
                ('rng_algorithm', models.CharField(max_length=40)),
                ('rng_seed', models.CharField(blank=True, max_length=128)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('record_hash', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_spin_log',
                'ordering': ['sequence_number'],
            },
        ),
    ]
