# Generated by Django 5.1.15 on 2026-08-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinauditlog',
            name='player_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Jugador interno; nulo en modo proveedor.', null=True),
        ),
        migrations.AlterField(
            model_name='spinauditlog',
            name='external_player_id',
            field=models.CharField(db_index=True, help_text='user_id del casino, o email/id del jugador interno.', max_length=120),
        ),
        migrations.AlterField(
            model_name='spinauditlog',
            name='operator_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Operador externo; nulo en modo plataforma propia.', null=True),
        ),
    ]
