# Generated by Django 5.1.15 on 2026-07-30 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_base_url', models.URLField(help_text='Endpoint base de la billetera del casino para debit/credit/rollback.')),
                ('allowed_iframe_origins', models.JSONField(default=list, help_text='Orígenes permitidos para embeber (CSP frame-ancestors y validación de postMessage).')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('jwt_verifying_key_ref', models.CharField(blank=True, help_text='Referencia (no el valor) a la clave pública/secreto para verificar tokens del operador.', max_length=200)),
                ('webhook_hmac_secret_ref', models.CharField(blank=True, help_text='Referencia al secreto HMAC para firmar/verificar webhooks.', max_length=200)),
            ],
            options={
                'db_table': 'wallet_operator',
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(help_text='Moneda origen, p.ej. EUR.', max_length=10)),
                ('quote_currency', models.CharField(help_text='Moneda destino, p.ej. USD.', max_length=10)),
                ('rate', models.DecimalField(decimal_places=12, help_text='1 unidad de base = `rate` unidades de quote.', max_digits=24)),
                ('source', models.CharField(help_text='Proveedor del tipo (ECB, openexchange, manual...).', max_length=60)),
                ('effective_at', models.DateTimeField(help_text='Momento en que este tipo entra en vigor.')),
            ],
            options={
                'db_table': 'wallet_fx_rate',
                'ordering': ['-effective_at'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'effective_at'], name='wallet_fx_r_base_cu_bf1222_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'effective_at', 'source'), name='uq_fx_rate_point')],
            },
        ),
        migrations.CreateModel(
            name='LaunchToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(help_text='Identificador único del token (claim jti).', max_length=128, unique=True)),
                ('external_player_id', models.CharField(help_text='ID del jugador en el casino.', max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Corta vida (p.ej. 30-120s).')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_tokens', to='app_game.game')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_tokens', to='app_wallet_integration.operator')),
            ],
            options={
                'db_table': 'wallet_launch_token',
            },
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_player_id', models.CharField(help_text='ID del jugador en el sistema del casino (user_id).', max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('launch_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_session', to='app_wallet_integration.launchtoken')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_sessions', to='app_wallet_integration.operator')),
            ],
            options={
                'db_table': 'wallet_player_session',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEBIT', 'Débito (apuesta)'), ('CREDIT', 'Crédito (premio)'), ('ROLLBACK', 'Reverso')], max_length=10)),
                ('amount', models.BigIntegerField(help_text='Monto en céntimos. Siempre >= 0.')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('idempotency_key', models.CharField(max_length=140)),
                ('external_reference', models.CharField(blank=True, help_text='Referencia devuelta por la billetera del casino.', max_length=140)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('FAILED', 'Fallida'), ('ROLLED_BACK', 'Revertida')], default='PENDING', max_length=12)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app_wallet_integration.operator')),
                ('player_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app_wallet_integration.playersession')),
                ('spin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app_game.spin')),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='launchtoken',
            index=models.Index(fields=['operator', 'is_used'], name='wallet_laun_operato_d3760d_idx'),
        ),
        migrations.AddIndex(
            model_name='playersession',
            index=models.Index(fields=['operator', 'external_player_id'], name='wallet_play_operato_34558d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['operator', 'status'], name='wallet_tran_operato_a6f039_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('operator', 'idempotency_key'), name='uq_wallet_tx_idempotency'),
        ),
    ]
