# Generated by Django 5.1.15 on 2026-08-14 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="Nombre para identificar la clave (ej. 'prod', 'staging').", max_length=80)),
                ('prefix', models.CharField(db_index=True, help_text='Parte visible de la clave (no secreta).', max_length=16)),
                ('hashed_key', models.CharField(help_text='Hash SHA-256 del secreto. Nunca el valor en claro.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='app_wallet_integration.operator')),
            ],
            options={
                'db_table': 'wallet_operator_api_key',
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='wallet_oper_prefix_ecf0dd_idx')],
            },
        ),
    ]
