# Generated by Django 5.1.15 on 2026-08-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet_integration', '0002_operatorapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='default_currency',
        ),
    ]
