# Generated by Django 5.1.15 on 2026-08-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet_integration', '0003_remove_operator_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='demo_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
