# Generated by Django 5.1.15 on 2026-08-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet_integration', '0004_playersession_demo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='wallet_mode',
            field=models.CharField(choices=[('DEMO', 'Demo (saldo interno fun-money)'), ('SEAMLESS', 'Seamless (billetera real del operador vía HTTP)')], default='DEMO', max_length=10),
        ),
    ]
