# Generated by Django 5.1.15 on 2026-08-01 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, help_text='Saldo en unidades menores (céntimos).')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_wallet',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLAYER', 'Jugador'), ('MASTER', 'Master')], default='PLAYER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_profile',
            },
        ),
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('MASTER_CREDIT', 'Crédito del master'), ('BET', 'Apuesta'), ('WIN', 'Premio'), ('ADJUSTMENT', 'Ajuste')], max_length=16)),
                ('delta', models.BigIntegerField(help_text='Variación con signo, en céntimos (+ acredita, - debita).')),
                ('balance_after', models.BigIntegerField(help_text='Saldo resultante tras aplicar el movimiento.')),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='app_accounts.playerwallet')),
            ],
            options={
                'db_table': 'account_balance_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'kind'], name='account_bal_wallet__fa41a6_idx')],
            },
        ),
    ]
