# Generated by Django 5.1.15 on 2026-08-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
        ('app_wallet_integration', '0004_playersession_demo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='app_wallet_integration.operator'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Jugador'), ('MASTER', 'Master'), ('OPERATOR', 'Operador')], default='PLAYER', max_length=10),
        ),
    ]
