# Generated by Django 5.1.15 on 2026-07-30 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_game', '0001_initial'),
        ('app_wallet_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('target_rtp', models.DecimalField(decimal_places=4, help_text='Fracción. Ej: 0.9600 = 96%.', max_digits=6)),
                ('house_margin', models.DecimalField(decimal_places=4, help_text='1 - target_rtp. Ej: 0.0400 = 4%.', max_digits=6)),
                ('math_version', models.CharField(help_text='Debe coincidir con ReelStrip.math_version certificado.', max_length=40)),
                ('certification_reference', models.CharField(blank=True, help_text='Nº de informe del laboratorio (GLI/iTech/BMM).', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(help_text='Inicio de vigencia.')),
                ('effective_to', models.DateTimeField(blank=True, help_text='Fin de vigencia (nulo = indefinido).', null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtp_configurations', to='app_game.game')),
                ('operator', models.ForeignKey(blank=True, help_text='Nulo = configuración por defecto del juego (sin override de operador).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp_configurations', to='app_wallet_integration.operator')),
            ],
            options={
                'db_table': 'rtp_configuration',
            },
        ),
        migrations.CreateModel(
            name='RTPChangeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rtp_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='app_rtp.rtpconfiguration')),
            ],
            options={
                'db_table': 'rtp_change_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rtpconfiguration',
            index=models.Index(fields=['game', 'operator', 'is_active'], name='rtp_configu_game_id_5c9c41_idx'),
        ),
    ]
