# Generated by Django 5.1.15 on 2026-07-30 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grid_cols', models.PositiveSmallIntegerField(default=3, help_text='Nº de rodillos (columnas). Ej.: 3, 5, 6.')),
                ('grid_rows', models.PositiveSmallIntegerField(default=3, help_text='Símbolos visibles por rodillo (filas). Ej.: 3, 4.')),
                ('win_mode', models.CharField(choices=[('LINES', 'Líneas de pago fijas'), ('WAYS', 'Ways to win (adyacencia en rodillos)')], default='LINES', help_text='LINES: líneas fijas (usa Payline). WAYS: adyacencia (ignora Payline).', max_length=10)),
                ('volatility', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('max_win_multiplier', models.PositiveIntegerField(default=1000, help_text='Tope de pago como múltiplo de la apuesta total.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'game',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(help_text='Identificador/orden de la línea (0..n).')),
                ('pattern', models.JSONField(help_text='Fila por rodillo, longitud = grid_cols. Ej. 3 rodillos: [0,0,0] fila superior, [0,1,2] diagonal. Ej. 5 rodillos: [1,1,1,1,1] fila central.')),
            ],
            options={
                'db_table': 'game_payline',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ReelStrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('math_version', models.CharField(help_text='Versión del modelo matemático (debe coincidir con la config RTP).', max_length=40)),
                ('reel_index', models.PositiveSmallIntegerField(help_text='Columna 0..cols-1.')),
                ('strip', models.JSONField(help_text="Lista ordenada de códigos de símbolo. Ej: ['A','K','WILD','A','Q',...].")),
            ],
            options={
                'db_table': 'game_reel_strip',
                'ordering': ['math_version', 'reel_index'],
            },
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('math_version', models.CharField(max_length=40)),
                ('bet_amount', models.BigIntegerField(help_text='Apuesta total en céntimos.')),
                ('win_amount', models.BigIntegerField(default=0, help_text='Premio total en céntimos.')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('lines_played', models.PositiveSmallIntegerField(default=1)),
                ('matrix_result', models.JSONField(help_text="Matriz 3x3 resultante. Ej: [['A','K','A'],['Q','WILD','Q'],['A','A','A']].")),
                ('winning_lines', models.JSONField(default=list, help_text='Detalle de líneas ganadoras y sus premios.')),
                ('rng_algorithm', models.CharField(default='secrets.SystemRandom', max_length=40)),
                ('rng_seed', models.CharField(blank=True, help_text='Semilla/estado para reproducibilidad y prueba.', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SETTLED', 'Liquidado'), ('VOIDED', 'Anulado')], default='PENDING', max_length=10)),
            ],
            options={
                'db_table': 'game_spin',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Identificador corto en la matriz: 'A', 'K', 'WILD'...", max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('asset_key', models.CharField(blank=True, help_text='Clave del sprite en el cliente Phaser.', max_length=120)),
                ('is_wild', models.BooleanField(default=False)),
                ('is_scatter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'game_symbol',
            },
        ),
        migrations.CreateModel(
            name='SymbolPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField(help_text='Nº de símbolos en línea (para 3x3 normalmente 3).')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Múltiplo de la apuesta por línea.', max_digits=10)),
            ],
            options={
                'db_table': 'game_symbol_payout',
            },
        ),
        migrations.CreateModel(
            name='DropJackpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trigger_probability', models.DecimalField(decimal_places=10, help_text='Prob. de disparo por tiro pagado. Ej: 0.0001000000 = 1 entre 10.000.', max_digits=12)),
                ('award_amount', models.BigIntegerField(help_text='Premio fijo en unidades menores (MVP).')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drop_jackpot', to='app_game.game')),
            ],
            options={
                'db_table': 'game_drop_jackpot',
            },
        ),
        migrations.CreateModel(
            name='GameBetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('min_bet', models.BigIntegerField(help_text='Apuesta mínima en unidades menores.')),
                ('max_bet', models.BigIntegerField(help_text='Apuesta máxima en unidades menores.')),
                ('default_bet', models.BigIntegerField(help_text='Apuesta por defecto en unidades menores.')),
                ('bet_levels', models.JSONField(default=list, help_text='Niveles de apuesta permitidos, en unidades menores. Ej: [50,100,200,500].')),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_profiles', to='app_game.game')),
            ],
            options={
                'db_table': 'game_bet_profile',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_open', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='app_game.game')),
            ],
            options={
                'db_table': 'game_session',
            },
        ),
    ]
