# Generated by Django 5.1.15 on 2026-07-30 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_game', '0001_initial'),
        ('app_rtp', '0001_initial'),
        ('app_wallet_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='app_wallet_integration.playersession'),
        ),
        migrations.AddField(
            model_name='payline',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylines', to='app_game.game'),
        ),
        migrations.AddField(
            model_name='reelstrip',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_strips', to='app_game.game'),
        ),
        migrations.AddField(
            model_name='spin',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='app_game.game'),
        ),
        migrations.AddField(
            model_name='spin',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='app_game.gamesession'),
        ),
        migrations.AddField(
            model_name='spin',
            name='rtp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='app_rtp.rtpconfiguration'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='app_game.game'),
        ),
        migrations.AddField(
            model_name='symbolpayout',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='app_game.game'),
        ),
        migrations.AddField(
            model_name='symbolpayout',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='app_game.symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='gamebetprofile',
            unique_together={('game', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='payline',
            unique_together={('game', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='reelstrip',
            unique_together={('game', 'math_version', 'reel_index')},
        ),
        migrations.AddIndex(
            model_name='spin',
            index=models.Index(fields=['game', 'created_at'], name='game_spin_game_id_c109a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('game', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='symbolpayout',
            unique_together={('game', 'symbol', 'count')},
        ),
    ]
