# Generated by Django 5.1.15 on 2026-08-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0002_initial'),
        ('app_wallet_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_user',
            field=models.ForeignKey(blank=True, help_text='Jugador interno (modo plataforma propia). Nulo si es operador externo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_session',
            field=models.ForeignKey(blank=True, help_text='Operador externo (modo proveedor). Nulo si es jugador interno.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='app_wallet_integration.playersession'),
        ),
    ]
