# Generated by Django 5.1.15 on 2026-08-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0003_gamesession_player_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_color',
            field=models.CharField(default='#0b0f1a', help_text='Color de fondo del tema.', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Plantilla base para crear casinos.'),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, help_text='Título mostrado en el cliente.', max_length=120),
        ),
        migrations.AddField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, help_text='Sprite del símbolo (tema).', null=True, upload_to='symbols/'),
        ),
    ]
