# Generated by Django 5.1.15 on 2026-08-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0004_game_background_color_game_is_template_game_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Fondo a pantalla completa.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo superior (sustituye al título).', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_off',
            field=models.ImageField(blank=True, help_text='Icono música silenciada.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_on',
            field=models.ImageField(blank=True, help_text='Icono música activada.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_track',
            field=models.FileField(blank=True, help_text='Pista de música de fondo (loop).', null=True, upload_to='themes/audio/'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_banner',
            field=models.ImageField(blank=True, help_text='Banner del premio (bajo la rejilla).', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='spin_button',
            field=models.ImageField(blank=True, help_text='Imagen del botón de girar.', null=True, upload_to='themes/'),
        ),
    ]
