# Generated by Django 5.1.15 on 2026-08-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0005_game_background_image_game_logo_game_music_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen de perfil (lobby).', null=True, upload_to='themes/thumbs/'),
        ),
    ]
