# Generated by Django 5.1.15 on 2026-08-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0006_game_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accent_color',
            field=models.CharField(default='#ffd23f', help_text='Color que predomina (marcos, glow, acentos).', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='auto_off',
            field=models.ImageField(blank=True, help_text='Botón autoplay inactivo.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='auto_on',
            field=models.ImageField(blank=True, help_text='Botón autoplay activo.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='background_gradient',
            field=models.CharField(blank=True, default='', help_text="Colores del degradado separados por coma. Ej: '#180a2e,#05030f'.", max_length=220),
        ),
        migrations.AddField(
            model_name='game',
            name='background_type',
            field=models.CharField(choices=[('COLOR', 'Color fijo'), ('GRADIENT', 'Degradado'), ('IMAGE', 'Imagen o GIF'), ('VIDEO', 'Video')], default='COLOR', help_text='Tipo de fondo: color, degradado, imagen/gif o video.', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='background_video',
            field=models.FileField(blank=True, help_text='Fondo en video (mp4/webm).', null=True, upload_to='themes/video/'),
        ),
        migrations.AddField(
            model_name='game',
            name='bet_minus',
            field=models.ImageField(blank=True, help_text='Botón bajar apuesta.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='bet_plus',
            field=models.ImageField(blank=True, help_text='Botón subir apuesta.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='turbo_off',
            field=models.ImageField(blank=True, help_text='Botón turbo inactivo.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='game',
            name='turbo_on',
            field=models.ImageField(blank=True, help_text='Botón turbo activo.', null=True, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Frecuencia del símbolo en la banda (mayor = más común, menos premio).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Fondo a pantalla completa (imagen o gif).', null=True, upload_to='themes/'),
        ),
    ]
