# Generated by Django 5.1.15 on 2026-08-14 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0007_game_accent_color_game_auto_off_game_auto_on_and_more'),
        ('app_wallet_integration', '0002_operatorapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='feature_state',
            field=models.JSONField(blank=True, default=dict, help_text="Estado de features con memoria (ej. {'free_spins': {'remaining': 7, 'multiplier': '3.00'}})."),
        ),
        migrations.CreateModel(
            name='FreeSpinsFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trigger_scatter_count', models.PositiveSmallIntegerField(default=3, help_text='Nº de scatters para disparar la ronda.')),
                ('spins_awarded', models.PositiveSmallIntegerField(default=10, help_text='Tiros gratis otorgados por disparo.')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Multiplicador aplicado a los premios de la ronda.', max_digits=6)),
                ('retrigger', models.BooleanField(default=True, help_text='Si juntar scatters durante la ronda añade más tiros.')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_spins', to='app_game.game')),
            ],
            options={
                'db_table': 'game_free_spins_feature',
            },
        ),
        migrations.CreateModel(
            name='OperatorGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Si el operador puede lanzar este juego ahora mismo.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en el lobby del operador.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='app_game.game')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app_wallet_integration.operator')),
            ],
            options={
                'db_table': 'operator_game',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('operator', 'game')},
            },
        ),
    ]
