# Generated by Django 5.1.15 on 2026-08-17 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0008_gamesession_feature_state_freespinsfeature_and_more'),
        ('app_wallet_integration', '0005_operator_wallet_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeRoundGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_player_id', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('bet_amount', models.BigIntegerField(help_text='Apuesta FIJA por ronda gratis (unidades menores).')),
                ('total', models.PositiveIntegerField(help_text='Tiradas gratis concedidas.')),
                ('remaining', models.PositiveIntegerField(help_text='Tiradas gratis sin consumir.')),
                ('win_multiplier', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('DEPLETED', 'Consumida'), ('EXPIRED', 'Caducada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Nulo = sin caducidad.', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_round_grants', to='app_game.game')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_round_grants', to='app_wallet_integration.operator')),
                ('player_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_round_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_free_round_grant',
                'indexes': [models.Index(fields=['operator', 'external_player_id', 'game', 'status'], name='game_free_r_operato_935cba_idx'), models.Index(fields=['player_user', 'game', 'status'], name='game_free_r_player__087fb8_idx')],
            },
        ),
    ]
